#!/usr/bin/env python3
"""Regenerate the README tap content from the Cask/Formula sources.

The `.rb` files under `Casks/` and `Formula/` are the single source of truth.
This script reads each one, extracts its name, version, description and
homepage, and rewrites every auto-generated region in README.md (the blocks
delimited by the `<!-- BEGIN:* -->` / `<!-- END:* -->` markers):

    install-tap     the `brew tap` + install commands, grouped by kind
    install-notap   the tap-less `brew install johnny4young/tap/...` commands
    casks           the casks version table
    formulae        the formulae version table

New casks or formulae appear automatically in all of these; nothing in the
generated regions needs to be edited by hand.

Usage:
    python3 scripts/sync-readme.py            # rewrite README.md in place
    python3 scripts/sync-readme.py --check    # exit 1 if README is out of date
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
README = REPO_ROOT / "README.md"

# One entry per artifact kind, in the order they should appear.
KINDS = [
    {
        "key": "casks",
        "dir": "Casks",
        "table_header": "Cask",
        "comment": "Casks (macOS apps)",
        "cask": True,
    },
    {
        "key": "formulae",
        "dir": "Formula",
        "table_header": "Formula",
        "comment": "Formulae (CLIs, macOS + Linux)",
        "cask": False,
    },
]

TAP = "johnny4young/tap"

# Pull a `field "value"` literal out of a Cask/Formula source. Both DSLs use
# the same `field "string"` form for the bits we surface.
_FIELD = r'^\s*{name}\s+"([^"]+)"'


def _field(text: str, name: str) -> str | None:
    match = re.search(_FIELD.format(name=re.escape(name)), text, re.MULTILINE)
    return match.group(1) if match else None


def parse_artifact(path: Path) -> dict[str, str]:
    """Extract the README-facing metadata from a single .rb file."""
    text = path.read_text(encoding="utf-8")
    name = path.stem  # filename stem == the cask/formula token
    version = _field(text, "version")
    desc = _field(text, "desc")
    homepage = _field(text, "homepage")

    missing = [
        label
        for label, value in (("version", version), ("desc", desc), ("homepage", homepage))
        if not value
    ]
    if missing:
        raise SystemExit(f"{path}: could not parse field(s): {', '.join(missing)}")

    return {"name": name, "version": version, "desc": desc, "homepage": homepage}


def load_kind(kind: dict) -> list[dict[str, str]]:
    """All artifacts of one kind, sorted by name."""
    src_dir = REPO_ROOT / kind["dir"]
    return sorted(
        (parse_artifact(p) for p in src_dir.glob("*.rb")),
        key=lambda a: a["name"],
    )


def render_table(kind: dict, artifacts: list[dict[str, str]]) -> str:
    """Build the Markdown version table for one kind."""
    header = kind["table_header"]
    lines = [
        f"| {header} | Version | Description | Upstream |",
        "| --- | --- | --- | --- |",
    ]
    if not artifacts:
        lines.append("| _none yet_ |  |  |  |")
    for a in artifacts:
        desc = a["desc"].replace("|", r"\|")
        lines.append(
            f"| `{a['name']}` | `{a['version']}` | {desc} | <{a['homepage']}> |"
        )
    return "\n".join(lines)


def render_install(by_kind: list[tuple[dict, list]], *, tapped: bool) -> str:
    """Build a fenced `brew install` block grouped by kind.

    `tapped` controls the command form: tapped uses short names (after
    `brew tap`), untapped uses the fully-qualified `johnny4young/tap/<name>`.
    """
    lines = ["```bash"]
    if tapped:
        lines.append(f"brew tap {TAP}")

    first_group = not tapped  # untapped block has no leading `brew tap` line
    for kind, artifacts in by_kind:
        if not artifacts:
            continue
        # Blank line between groups (and after the `brew tap` line).
        if not first_group or tapped:
            lines.append("")
        first_group = False
        lines.append(f"# {kind['comment']}")
        for a in artifacts:
            ref = a["name"] if tapped else f"{TAP}/{a['name']}"
            cmd = f"brew install --cask {ref}" if kind["cask"] else f"brew install {ref}"
            lines.append(cmd)

    lines.append("```")
    return "\n".join(lines)


def replace_region(content: str, key: str, body: str) -> str:
    begin = f"<!-- BEGIN:{key} (auto-generated by scripts/sync-readme.py — do not edit) -->"
    end = f"<!-- END:{key} -->"
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
    if not pattern.search(content):
        raise SystemExit(
            f"README.md is missing the '{key}' markers:\n  {begin}\n  {end}"
        )
    return pattern.sub(f"{begin}\n{body}\n{end}", content)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if README.md is out of date instead of rewriting it",
    )
    args = parser.parse_args()

    by_kind = [(kind, load_kind(kind)) for kind in KINDS]

    regions = {
        "install-tap": render_install(by_kind, tapped=True),
        "install-notap": render_install(by_kind, tapped=False),
    }
    for kind, artifacts in by_kind:
        regions[kind["key"]] = render_table(kind, artifacts)

    original = README.read_text(encoding="utf-8")
    updated = original
    for key, body in regions.items():
        updated = replace_region(updated, key, body)

    if updated == original:
        print("README.md is up to date.")
        return 0

    if args.check:
        print("README.md is out of date — run: python3 scripts/sync-readme.py", file=sys.stderr)
        return 1

    README.write_text(updated, encoding="utf-8")
    print("README.md updated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
